### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by C1rdec** [Willy-Kimura/SharpClipboard#9]
Sometimes the unhandled exception box appears. I did not find the pattern to reproduce the issue but I'll keep you posted.

**Comment by Willy-Kimura** [comment]
Great, keep me posted.
And to be specific, is this only happening in the latest release?

**Comment by C1rdec** [comment]
![image](https://user-images.githubusercontent.com/5436436/79993038-4cf59800-8482-11ea-9a59-7fc8afd39a09.png)



Here is the full stack trace:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

```
```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at WK.Libraries.SharpClipboardNS.Views.ClipboardHandle.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
PoeLurker
    Assembly Version: 1.5.19.0
    Win32 Version: 1.5.19.0
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/PoeLurker.exe
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Caliburn.Micro.Platform
    Assembly Version: 3.2.0.0
    Win32 Version: 3.2.0.0
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/Caliburn.Micro.Platform.DLL
----------------------------------------
Caliburn.Micro
    Assembly Version: 3.2.0.0
    Win32 Version: 3.2.0.0
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/Caliburn.Micro.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.Threading.Tasks
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Threading.Tasks/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.Tasks.dll
----------------------------------------
Caliburn.Micro.Platform.Core
    Assembly Version: 3.2.0.0
    Win32 Version: 3.2.0.0
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/Caliburn.Micro.Platform.Core.DLL
----------------------------------------
System.Reflection
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Reflection/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.dll
----------------------------------------
System.Collections
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ObjectModel/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ObjectModel.dll
----------------------------------------
System.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Linq/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.dll
----------------------------------------
MahApps.Metro
    Assembly Version: 1.6.5.1
    Win32 Version: 1.6.5.0
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/MahApps.Metro.DLL
----------------------------------------
LiveCharts
    Assembly Version: 0.9.7.0
    Win32 Version: 0.9.7
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/LiveCharts.DLL
----------------------------------------
Lurker
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/Lurker.DLL
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
System.Resources.ResourceManager
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Resources.ResourceManager/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Resources.ResourceManager.dll
----------------------------------------
NLog
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.8.10751
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/NLog.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
Sentry
    Assembly Version: 2.1.1.0
    Win32 Version: 2.1.1.0
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/Sentry.DLL
----------------------------------------
Sentry.Protocol
    Assembly Version: 2.1.1.0
    Win32 Version: 2.1.1.0
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/Sentry.Protocol.DLL
----------------------------------------
System.Reflection.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Reflection.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.Extensions.dll
----------------------------------------
ConfOxide
    Assembly Version: 1.4.2.0
    Win32 Version: 1.4.2.0
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/ConfOxide.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 1.2.3.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/System.Collections.Immutable.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
WindowsInput
    Assembly Version: 1.0.4.0
    Win32 Version: 1.0.4.0
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/WindowsInput.DLL
----------------------------------------
System.Threading
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Threading/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.dll
----------------------------------------
Lurker.Patreon
    Assembly Version: 1.0.16.0
    Win32 Version: 1.0.16.0
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/Lurker.Patreon.DLL
----------------------------------------
SharpClipboard
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/SharpClipboard.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Gma.System.MouseKeyHook
    Assembly Version: 5.6.130.0
    Win32 Version: 5.6.130.0
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/Gma.System.MouseKeyHook.DLL
----------------------------------------
Squirrel
    Assembly Version: 1.9.1.0
    Win32 Version: 1.9.1.0
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/Squirrel.DLL
----------------------------------------
Splat
    Assembly Version: 1.6.2.0
    Win32 Version: 1.6.2
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/Splat.DLL
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Text.RegularExpressions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Text.RegularExpressions.dll
----------------------------------------
Hardcodet.Wpf.TaskbarNotification
    Assembly Version: 1.0.5.0
    Win32 Version: 1.0.5.0
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/Hardcodet.Wpf.TaskbarNotification.DLL
----------------------------------------
System.Windows.Interactivity
    Assembly Version: 4.5.0.0
    Win32 Version: 3.0.40218.0
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/System.Windows.Interactivity.DLL
----------------------------------------
PresentationFramework-SystemCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemCore/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemCore.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Linq.Expressions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.Expressions.dll
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
NuGet.Squirrel
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/NuGet.Squirrel.DLL
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
LiteDB
    Assembly Version: 5.0.4.0
    Win32 Version: 5.0.4
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/LiteDB.DLL
----------------------------------------
LiveCharts.Wpf
    Assembly Version: 0.9.7.0
    Win32 Version: 0.9.7
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/LiveCharts.Wpf.DLL
----------------------------------------
ControlzEx
    Assembly Version: 3.0.2.4
    Win32 Version: 3.0.2.4
    CodeBase: file:///C:/Users/cedri/AppData/Local/PoeLurker/app-1.5.19/ControlzEx.DLL
----------------------------------------
PresentationFramework-SystemData
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemData/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemData.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by C1rdec** [comment]
This exception happens when I copy text out of my remote computer.

**Comment by Willy-Kimura** [comment]
I see, kindly try testing this scenario with the latest release...

**Comment by C1rdec** [comment]
I was on the package Nuget 3.3.0. Just updated to 3.5.0 will keep you posted. Have you change something regarding blob? were can we found the release note of nuget package ?

**Comment by Willy-Kimura** [comment]
Great, okay.

I've not modified blob-objects-detection in the clipboard so this should not be an issue. 
You can find the release notes for each version selected on NuGet via the **Release Notes** section.

**Comment by C1rdec** [comment]
It's something around images

**Comment by kevklam** [comment]
I've run into similar (possibly the same) issues on 3.3.0. Intermittent, and agreed that anecdotally it seems remote desktop is a contributing factor although I believe I've also seen it happen without remote desktop being involved. I've updated to 3.5.0 now, fingers crossed that the issue magically goes away.

**Comment by Willy-Kimura** [comment]
@kevklam Have you confirmed it's working in `3.5.0`?

**Comment by C1rdec** [comment]
I haven't been able to reproduce the issue since I updated from 3.3.0 to 3.5.0. I'll keep you posted I think we can close this issue for now.

**Comment by Willy-Kimura** [comment]
Ok, great.
